### ISSUE TITLE
Support to convert xlookup -> INDEX/Match

### ISSUE THREAD

**Issue by gyutaepark** [alexbogun/xlookup_replace#1]
Hi. The code functionality seems amazing so far.
Would you also consider adding xlookup -> index/match?

The main reason where this would be useful is for cross-compatibility between libreoffice calc and excel where libreoffice does not support xlookups at all but would support index/match.

Thanks.

**Comment by alexbogun** [comment]
It is already implemented, have a look at read-me again or just have a look at the code

**Comment by alexbogun** [comment]
sorry misread your question if you want to replace xlookup, just modify the code to look for "xlookup" instead of "vlookup". Cheers
